version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - mvn install
  post_build:
    commands:
      - echo completed
artifacts:
  files:
    - target/TweetApp.jar
